import Head from 'next/head';
// import Link from 'next/link';
// import Image from 'next/image';
// import {
//   Breadcrumb,
//   BreadcrumbItem,
//   Button,
//   Tabs,
//   Tab,
// } from 'carbon-components-react';
// // eslint-disable-next-line camelcase
// import { Solve, Earth, SocialWork_01 } from '@carbon/pictograms-react';
// import { Home16 } from '@carbon/icons-react';
// import { InfoSection, InfoCard } from '../components/Info';
// import Illo from '../public/tab-illo.png';

export default function About() {
  const props = {
    tabs: {
      selected: 0,
      role: 'navigation',
    },
    tab: {
      role: 'presentation',
      tabIndex: 0,
    },
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div>
        <div className="bx--row landing-page__banner">
          <div className="bx--col-lg-16">
            <Breadcrumb noTrailingSlash aria-label="Page navigation">
              <BreadcrumbItem>
                <Link href="/" passHref>
                  <Home16 />
                </Link>
              </BreadcrumbItem>
              <BreadcrumbItem>
                <Link href="/about">About</Link>
              </BreadcrumbItem>
            </Breadcrumb>
            <h1 className="landing-page__heading">Film Lab.</h1>
            <h2 className="landing-page__subtitle">
              A lightweight ERP for film process labs.
            </h2>
          </div>
        </div>

        <div className="bx--row landing-page__r2">
          <div className="bx--col bx--no-gutter">
            <Tabs {...props.tabs} aria-label="Tab navigation">
              <Tab {...props.tab} label="About">
                <div className="bx--grid bx--grid--no-gutter bx--grid--full-width">
                  <div className="bx--row landing-page__tab-content">
                    <div className="bx--col-md-4 bx--col-lg-6">
                      <h2 className="landing-page__subheading">
                        What is Film Lab?
                      </h2>
                      <p className="landing-page__p">
                        Carbon is IBM’s open-source design system for digital
                        products and experiences. With the IBM Design Language
                        as its foundation, the system consists of working code,
                        design tools and resources, human interface guidelines,
                        and a vibrant community of contributors.
                      </p>
                      <Button>Learn more</Button>
                    </div>
                    <div className="bx--col-md-4 bx--offset-lg-1 bx--col-lg-5">
                      <div className="landing-page__illo">
                        <Image
                          // className="landing-page__illo"
                          src={Illo}
                          alt="Carbon illustration"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </Tab>
              <Tab {...props.tab} label="Design">
                <div className="bx--grid bx--grid--no-gutter bx--grid--full-width">
                  <div className="bx--row landing-page__tab-content">
                    <div className="bx--col-lg-16">
                      Rapidly build beautiful and accessible experiences. The
                      Carbon kit contains all resources you need to get started.
                    </div>
                  </div>
                </div>
              </Tab>
              <Tab {...props.tab} label="Develop">
                <div className="bx--grid bx--grid--no-gutter bx--grid--full-width">
                  <div className="bx--row landing-page__tab-content">
                    <div className="bx--col-lg-16">
                      Carbon provides styles and components in Vanilla, React,
                      Angular, and Vue for anyone building on the web.
                    </div>
                  </div>
                </div>
              </Tab>
            </Tabs>
          </div>
        </div>

        <InfoSection heading="The Principles" className="landing-page__r3">
          <InfoCard
            heading="Carbon is Open"
            body="It's a distributed effort, guided by the principles of the open-source movement. Carbon's users are also it's makers, and everyone is encouraged to contribute."
          >
            <SocialWork_01 aria-label="Social Work" />
          </InfoCard>
          <InfoCard
            heading="Carbon is Modular"
            body="Carbon's modularity ensures maximum flexibility in execution. It's components are designed to work seamlessly with each other, in whichever combination suits the needs of the user."
          >
            <Solve aria-label="Solve" />
          </InfoCard>
          <InfoCard
            heading="Carbon is Consistent"
            body="Based on the comprehensive IBM Design Language, every element and component of Carbon was designed from the ground up to work elegantly together to ensure consistent, cohesive user experiences."
          >
            <Earth aria-label="Earth" />
          </InfoCard>
        </InfoSection>
      </div> */}
    </>
  );
}
